export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_MATERIAL_DATA: 'SET_MATERIAL_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_MATERIAL_DATA: 'RESET_MATERIAL_DATA',
	SHOW_LOADER: 'SHOW_LOADER',
	HIDE_LOADER: 'HIDE_LOADER',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
